package com.project.customer;


import javax.persistence.*;


/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "project")
public class Customer implements java.io.Serializable {

	private int idcustomer;
	private String cname;
	private String c_address;
	private String c_city;
	private String c_state;
	private long contact;
	private String userid;
	private int password;
	private String email;
	

	public Customer() {
		
	}


	public Customer(int idcustomer, String cname, String c_address, String c_city, String c_state, long contact,
			String userid, int password, String email) {
		super();
		this.idcustomer = idcustomer;
		this.cname = cname;
		this.c_address = c_address;
		this.c_city = c_city;
		this.c_state = c_state;
		this.contact = contact;
		this.userid = userid;
		this.password = password;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getIdcustomer() {
		return idcustomer;
	}


	public void setIdcustomer(int idcustomer) {
		this.idcustomer = idcustomer;
	}


	public String getCname() {
		return cname;
	}


	public void setCname(String cname) {
		this.cname = cname;
	}


	public String getC_address() {
		return c_address;
	}


	public void setC_address(String c_address) {
		this.c_address = c_address;
	}


	public String getC_city() {
		return c_city;
	}


	public void setC_city(String c_city) {
		this.c_city = c_city;
	}


	public String getC_state() {
		return c_state;
	}


	public void setC_state(String c_state) {
		this.c_state = c_state;
	}


	public long getContact() {
		return contact;
	}


	public void setContact(long contact) {
		this.contact = contact;
	}


	public String getUserid() {
		return userid;
	}


	public void setUserid(String userid) {
		this.userid = userid;
	}


	public int getPassword() {
		return password;
	}


	public void setPassword(int password) {
		this.password = password;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	@Override
	public String toString() {
		return "Customer [idcustomer=" + idcustomer + ", cname=" + cname + ", c_address=" + c_address + ", c_city="
				+ c_city + ", c_state=" + c_state + ", contact=" + contact + ", userid=" + userid + ", password="
				+ password + ", email=" + email + "]";
	}


}
	
	


	
