package com.project.employee;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "project")
public class Employee implements java.io.Serializable {

	private int eid;
	private String ename;
	private String edesig;
	private String e_address;
	private int idhotel;
	private String userid;
	private String password;
	

	public Employee() {
		
	}


	public Employee(int eid, String ename, String edesig, String e_address, int idhotel, String userid, String password) {
		super();
		this.eid = eid;
		this.ename = ename;
		this.edesig = edesig;
		this.e_address = e_address;
		this.idhotel = idhotel;
		this.userid = userid;
		this.password = password;
	}

    @Id
	public int getEid() {
		return eid;
	}


	public void setEid(int eid) {
		this.eid = eid;
	}


	public String getEname() {
		return ename;
	}


	public void setEname(String ename) {
		this.ename = ename;
	}


	public String getEdesig() {
		return edesig;
	}


	public void setEdesig(String edesig) {
		this.edesig = edesig;
	}


	public String getE_address() {
		return e_address;
	}


	public void setE_address(String e_address) {
		this.e_address = e_address;
	}


	public int getIdhotel() {
		return idhotel;
	}


	public void setIdhotel(int idhotel) {
		this.idhotel = idhotel;
	}


	public String getUserid() {
		return userid;
	}


	public void setUserid(String userid) {
		this.userid = userid;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}
	
	}

	
	


	
